/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./../src/components/modals/BaseModal.vue')['default']
    Card: typeof import('./../src/components/Card.vue')['default']
    MarketCard: typeof import('./../src/components/MarketCard.vue')['default']
    MarketChart: typeof import('./../src/components/MarketChart.vue')['default']
    ModalsController: typeof import('./../src/components/modals/ModalsController.vue')['default']
    Navbar: typeof import('./../src/components/Navbar.vue')['default']
    NumberInput: typeof import('./../src/components/NumberInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectAccountModal: typeof import('./../src/components/modals/SelectAccountModal.vue')['default']
    ThemeChange: typeof import('./../src/components/ThemeChange/index.vue')['default']
    WalletButton: typeof import('./../src/components/WalletButton.vue')['default']
  }
}
